const logo = '<img class="logo" src="../../assets/logo-light.svg" alt="AYRES Pet Supply">';
const progress = n => `<div class="progress"><strong>${String(n).padStart(2,'0')}</strong> / 07</div>`;
const micro = '<svg class="micro" viewBox="0 0 120 120" fill="none" aria-hidden="true"><g stroke="currentColor" stroke-width="4" stroke-linecap="round"><circle cx="60" cy="60" r="28"/><path d="M60 18v12M60 90v12M18 60h12M90 60h12M30 30l9 9M81 81l9 9M90 30l-9 9M39 81l-9 9"/></g><g fill="currentColor"><circle cx="50" cy="52" r="5"/><circle cx="69" cy="47" r="4"/><circle cx="70" cy="69" r="6"/><circle cx="48" cy="72" r="3"/></g></svg>';
const slides = [
`<article class="slide cover"><img class="photo" src="../../media/backgrounds/raw/camylla-battani-AoqgGAqrLpU-unsplash.jpg" alt="Perra activa levantando una pata">${logo}${progress(1)}<div class="cover-copy"><div class="eyebrow">PROBIÓTICOS PARA PERROS</div><h1>¿Tu perro tiene la panza sensible?</h1><p>Esto puede ser la clave <span>🦠✨</span></p></div><div class="swipe">DESLIZÁ <b>→</b></div></article>`,
`<article class="slide light">${logo}${progress(2)}<div class="orb orb-a">${micro}</div><div class="orb orb-b">${micro}</div><section class="content definition"><div class="eyebrow">MICROBIOTA INTESTINAL</div><h2>¿Qué son los probióticos?</h2><p class="lead">Son microorganismos vivos que viven en el intestino del perro.</p><p>Ayudan a mantener el equilibrio de la microbiota intestinal, mejoran la digestión y la absorción de nutrientes.</p><div class="highlight"><strong>Son por miles de millones</strong> y trabajan silenciosamente a favor de su salud.</div></section></article>`,
`<article class="slide dark">${logo}${progress(3)}<section class="content benefits"><div class="eyebrow">BENEFICIOS COMPROBADOS</div><h2>¿Para qué sirven?</h2><div class="benefit-grid"><div><span>🦠</span><p>Equilibran la<br><strong>flora intestinal</strong></p></div><div><span>💪</span><p>Fortalecen el<br><strong>sistema inmunológico</strong></p></div><div><span>✨</span><p>Mejoran el estado<br><strong>del pelaje</strong></p></div><div><span>⚡</span><p>Aumentan la<br><strong>energía general</strong></p></div></div></section></article>`,
`<article class="slide photo-slide vet"><img class="photo" src="../../media/backgrounds/raw/noppon-meenuch-FDKOuzy2QjM-unsplash.jpg" alt="Cachorro durante un control de salud">${logo}${progress(4)}<section class="photo-copy"><div class="eyebrow">EN MOMENTOS CLAVE</div><h2>¿Cuándo darlos?</h2><p>Son especialmente útiles cuando:</p><ul><li>Hay <strong>diarrea o problemas digestivos</strong> frecuentes.</li><li>El perro tomó <strong>antibióticos</strong>, que eliminan bacterias buenas.</li><li>Hay <strong>situaciones de estrés</strong>: mudanzas o cambios de rutina.</li></ul><div class="vet-note">✚ Siempre con indicación veterinaria</div></section></article>`,
`<article class="slide light timeline-slide">${logo}${progress(5)}<section class="content"><div class="eyebrow">USO REGULAR</div><h2>¿Cuándo ver resultados?</h2><p class="lead">La paciencia es clave.</p><div class="timeline"><div class="line"></div><div class="tick active"><b>HOY</b><span>Inicio</span></div><div class="tick"><b>SEMANA 1</b><span>Adaptación</span></div><div class="tick active"><b>ALGUNAS SEMANAS</b><span>Beneficios visibles</span></div></div><p>Los beneficios suelen notarse luego de algunas semanas de uso regular.</p><div class="fine">El tiempo varía según la edad del perro, su condición de salud y las dosis indicadas por el veterinario.</div></section></article>`,
`<article class="slide dark choice">${logo}${progress(6)}<section class="content"><div class="eyebrow">ELECCIÓN RESPONSABLE</div><h2>Cómo elegirlos bien</h2><div class="selection-guide"><div class="selection-number">03</div><div><strong>CLAVES PARA ELEGIR</strong><span>Información, formulación y acompañamiento profesional.</span></div><div class="selection-mark">✓</div></div><p class="intro">Antes de comprar cualquier producto:</p><ul><li>Consultá siempre con el <strong>veterinario.</strong></li><li>Verificá que esté formulado específicamente <strong>para perros.</strong></li><li>No todos los probióticos humanos son <strong>seguros para mascotas.</strong></li></ul></section></article>`,
`<article class="slide cta dark">${logo}${progress(7)}<section class="cta-center">${micro}<div class="eyebrow">SALUD DESDE ADENTRO</div><h2>La salud digestiva de tu perro empieza por una buena alimentación. 🐾</h2><p class="save">Guardá este post si tu perro tiene la panza sensible.</p><div class="question">💬 ¿Alguna vez le diste probióticos?<br><strong>¿Notaste mejoría?</strong></div><div class="socials"><span>@ayres.petsupply</span><b>ayrespetsupply.com</b></div></section></article>`
];
const requested = Number(new URLSearchParams(location.search).get('slide') || 1);
document.querySelector('#app').innerHTML = slides[Math.min(Math.max(requested,1),7)-1];
