const logo='<img class="logo" src="../../assets/logo-light.svg" alt="AYRES Pet Supply">';
const page=n=>`<div class="page"><b>${String(n).padStart(2,'0')}</b> / 06</div>`;
const joint=`<svg class="joint" viewBox="0 0 260 260" fill="none" aria-hidden="true"><path d="M68 24c4 42 28 73 47 91-10 13-14 29-10 44l-45 70" stroke="currentColor" stroke-width="25" stroke-linecap="round"/><path d="M190 24c-4 42-28 73-47 91 10 13 14 29 10 44l45 70" stroke="currentColor" stroke-width="25" stroke-linecap="round"/><circle cx="129" cy="135" r="42" stroke="#3db870" stroke-width="5"/><circle cx="129" cy="135" r="58" stroke="#3db870" stroke-width="2" stroke-dasharray="7 9"/></svg>`;
const slides=[
`<article class="slide cover"><img class="photo" src="assets/dog-running.png" alt="Perro corriendo en un parque">${logo}${page(1)}<section><div class="eyebrow">MOVILIDAD Y BIENESTAR</div><h1>¿Tu perro ya no corre <em>como antes?</em></h1><p>Sus articulaciones pueden estar pidiendo ayuda <span>🦴</span></p></section><div class="swipe">DESLIZÁ <b>→</b></div></article>`,
`<article class="slide light importance">${logo}${page(2)}<section><div class="visual">${joint}<span>ARTICULACIÓN<br>CANINA</span></div><div class="copy"><div class="eyebrow">MOVIMIENTO ES VIDA</div><h2>¿Por qué son tan importantes?</h2><p>Las articulaciones son las uniones móviles que le permiten a tu perro <strong>saltar, correr y jugar.</strong></p><p>Sin articulaciones sanas, su calidad de vida se reduce drásticamente.</p><div class="highlight">Los perros con mayor actividad física son los más vulnerables.</div></div></section></article>`,
`<article class="slide dark alerts">${logo}${page(3)}<section><div class="eyebrow">SEÑALES DE ALERTA</div><h2>Chequeá sus movimientos</h2><p class="intro">¿Tu perro muestra alguno de estos signos?</p><div class="alert-grid"><div><strong class="signal">⏸️</strong><span>No quiere moverse, jugar ni completar sus paseos.</span><i>×</i></div><div><strong class="signal">🐾</strong><span>Camina con dificultad, cojea o tiembla.</span><i>×</i></div><div><strong class="signal">🪜</strong><span>Evita subir o bajar escaleras.</span><i>×</i></div></div><p class="vet">✚ Si notás alguno, consultá al veterinario sin esperar.</p></section></article>`,
`<article class="slide age"><img class="photo" src="assets/senior-dog.png" alt="Perro mayor descansando en el parque">${logo}${page(4)}<section><div class="eyebrow">PREVENCIÓN TEMPRANA</div><h2>¿A qué edad aparecen los problemas?</h2><p>Los perros mayores son los más afectados, pero <strong>razas grandes y perros con sobrepeso</strong> también pueden tener problemas articulares desde jóvenes.</p><div class="highlight"><b>LA DIFERENCIA</b> Prevenir desde temprano.</div></section></article>`,
`<article class="slide nutrition"><img class="photo" src="assets/kibble-bowl.png" alt="Bowl con alimento balanceado">${logo}${page(5)}<section><div class="eyebrow">SOPORTE DESDE ADENTRO</div><h2>El rol de la nutrición</h2><p class="lead">Una dieta adecuada puede proteger las articulaciones.</p><p>Existen alimentos formulados con nutrientes específicos para el soporte articular.</p><div class="vet-card"><b>INDICACIÓN PROFESIONAL</b><span>El veterinario puede recomendar la mejor opción según la edad y el tamaño de tu perro.</span></div></section></article>`,
`<article class="slide cta dark">${page(6)}<section><img src="../../assets/logo-light.svg" alt="AYRES Pet Supply"><div class="line"></div><h2>Cuidar sus articulaciones es cuidar su <em>calidad de vida.</em> 🐾</h2><p>Guardá este post y revisá los movimientos de tu perro esta semana.</p><div class="comment">💬 ¿Tu perro tiene problemas de movilidad?<br>Contanos en los comentarios.</div><footer><span>@ayres.petsupply</span><b>ayrespetsupply.com</b></footer></section></article>`
];
const requested=Number(new URLSearchParams(location.search).get('slide')||1);document.querySelector('#app').innerHTML=slides[Math.min(Math.max(requested,1),slides.length)-1];
