const logo = '<img class="logo" src="../../../../../assets/logo-dark.svg" alt="AYRES Pet Supply">';
const page = (n) => `<div class="page"><b>${String(n).padStart(2, '0')}</b> / 09</div>`;
const eyebrow = (text) => `<div class="eyebrow">${text}</div>`;

const slides = [
  `<article class="slide cover"><img class="photo" src="assets/viaje-seguro-auto.png" alt="Perro con arnés de seguridad y gato en transportadora dentro de un auto"><div class="overlay"></div>${logo}${page(1)}<section>${eyebrow('P04 · VIAJES / BIENESTAR')}<h1>Viajar con tu mascota:<br><em>checklist antes de salir</em></h1></section><div class="swipe">DESLIZÁ <b>→</b></div></article>`,
  `<article class="slide light documents">${logo}${page(2)}<section>${eyebrow('DOCUMENTACIÓN PRIMERO')}<h2>Todo en regla,<br>antes de arrancar.</h2><div class="document-grid"><div><b>01</b><span>VACUNAS<br>AL DÍA</span></div><div><b>02</b><span>IDENTIFICACIÓN<br>VISIBLE</span></div><div><b>03</b><span>REQUISITOS<br>DEL DESTINO</span></div></div><p>Confirmá con tiempo los requisitos sanitarios del lugar al que viajás.</p></section></article>`,
  `<article class="slide kit"><img class="photo" src="assets/bolso-viaje-mascota.png" alt="Bolso y elementos esenciales para viajar con una mascota"><div class="overlay"></div>${logo}${page(3)}<section>${eyebrow('ARMÁ SU BOLSO')}<h2>Lo esencial<br>también viaja.</h2><div class="kit-grid"><span>AGUA</span><span>BEBEDERO</span><span>CORREA</span><span>BOLSAS</span><span>ALIMENTO HABITUAL</span><span>MEDICACIÓN INDICADA</span><span>MANTA</span><span>OBJETO FAMILIAR</span></div></section></article>`,
  `<article class="slide light lodging">${logo}${page(4)}<section>${eyebrow('ALOJAMIENTO PET FRIENDLY')}<h2>Confirmá antes<br>de reservar.</h2><div class="lodging-list"><div><b>01</b><span><strong>REGLAS</strong>Condiciones de ingreso y permanencia.</span></div><div><b>02</b><span><strong>ESPACIOS</strong>Dónde puede estar tu mascota.</span></div><div><b>03</b><span><strong>SERVICIOS CERCANOS</strong>Veterinaria, paseos y comercios.</span></div></div></section></article>`,
  `<article class="slide restraint"><img class="photo" src="assets/viaje-seguro-auto.png" alt="Mascotas viajando con sistemas de retención"><div class="overlay"></div>${logo}${page(5)}<section>${eyebrow('SEGURIDAD EN EL AUTO')}<h2>Que viaje cómodo.<br><em>Y bien sujeto.</em></h2><div class="restraint-options"><div><b>TRANSPORTADORA</b><span>Del tamaño adecuado y correctamente sujeta.</span></div><div><b>SISTEMA DE RETENCIÓN</b><span>Apto para su tamaño y bien colocado.</span></div></div><p>Nunca permitas que viaje suelto.</p></section></article>`,
  `<article class="slide light stops">${logo}${page(6)}<section>${eyebrow('PARADAS PLANIFICADAS')}<div class="time">2 <i>o</i> 3 <small>HORAS</small></div><h2>Una pausa también<br>es parte del viaje.</h2><div class="stop-grid"><div><b>01</b><span>AGUA</span></div><div><b>02</b><span>MOVIMIENTO</span></div><div><b>03</b><span>NECESIDADES</span></div></div><p>Ajustá la frecuencia según el animal y la duración del trayecto.</p></section></article>`,
  `<article class="slide dark never">${logo}${page(7)}<section>${eyebrow('DOS NO NEGOCIABLES')}<h2>Protegelo durante<br>todo el trayecto.</h2><div class="never-grid"><div><span>NUNCA</span><b>SOLO DENTRO<br>DEL VEHÍCULO</b><p>La temperatura puede volverse peligrosa rápidamente.</p></div><div><span>VENTANILLA</span><b>CERRADA Y<br>VIAJE SEGURO</b><p>No permitas que saque la cabeza mientras circulan.</p></div></div></section></article>`,
  `<article class="slide light vet">${logo}${page(8)}<section>${eyebrow('MAREO, ESTRÉS O ANGUSTIA')}<h2>No lo mediques<br>por tu cuenta.</h2><div class="vet-card"><b>ANTES DEL VIAJE</b><p>Si suele marearse o angustiarse, consultá con su veterinario para preparar el traslado.</p></div><div class="vet-rule"><span>NO SEDES SIN INDICACIÓN</span><i></i><span>CONSULTÁ ANTES</span></div></section></article>`,
  `<article class="slide closing"><img class="photo" src="assets/bolso-viaje-mascota.png" alt="Mascota junto a su equipo preparado para viajar"><div class="overlay"></div>${page(9)}<section>${logo}<div class="line"></div>${eyebrow('UN VIAJE SEGURO EMPIEZA ANTES')}<h2>Probá el equipo y hacé trayectos cortos antes de partir.</h2><p>Preparar la experiencia con tiempo también cuida su bienestar.</p><div class="cta">GUARDÁ LA CHECKLIST PARA TU PRÓXIMA ESCAPADA</div><footer><span>@ayres.petsupply</span><b>ayrespetsupply.com</b></footer></section></article>`,
];

const requested = Number(new URLSearchParams(window.location.search).get('slide') || 1);
const index = Math.min(Math.max(requested, 1), slides.length) - 1;
document.querySelector('#app').innerHTML = slides[index];
