const logo='<img class="logo" src="../../assets/logo-light.svg" alt="AYRES Pet Supply">';
const page=n=>`<div class="page"><b>${String(n).padStart(2,'0')}</b> / 07</div>`;
const slides=[
`<article class="slide cover"><img class="photo" src="assets/training-cover.png" alt="Persona entrenando a su perro al aire libre">${logo}${page(1)}<section><div class="eyebrow">ADIESTRAMIENTO CANINO</div><h1><em>5 comandos</em> que todo perro debería saber</h1><p>Y cómo enseñárselos <span>🎓🐕</span></p></section><div class="swipe">DESLIZÁ <b>→</b></div></article>`,
`<article class="slide light">${logo}${page(2)}<section class="why"><div class="eyebrow">APRENDER JUGANDO</div><h2>¿Por qué adiestrar?</h2><p class="lead">No es solo para “perros difíciles”.</p><div class="benefits"><div><i>↗</i><span>Aumenta la <strong>confianza</strong> del perro</span></div><div><i>⌂</i><span>Mejora la <strong>convivencia</strong> en casa</span></div><div><i>♥</i><span>Fortalece el <strong>vínculo</strong> entre vos y tu compañero</span></div></div><p class="tip"><b>EL SECRETO</b> Que aprenda jugando y asocie cada comando positivamente.</p></section></article>`,
`<article class="slide sit"><img class="photo" src="assets/training-cover.png" alt="Perro sentado frente a su tutora">${logo}${page(3)}<section><div class="eyebrow">COMANDO 01</div><h2>“Sentate”</h2><ol><li><b>1</b><span>Llamá su atención.</span></li><li><b>2</b><span>Sostené un trocito de comida frente a su nariz.</span></li><li><b>3</b><span>Decí “Sentate” y mové el premio hacia atrás, sobre su cabeza.</span></li><li><b>4</b><span>Cuando se siente, recompensalo de inmediato. 🎉</span></li></ol></section></article>`,
`<article class="slide dark">${logo}${page(4)}<section class="essentials"><div class="eyebrow">SEGURIDAD Y CONVIVENCIA</div><h2>Los 5 que no pueden faltar</h2><div class="commands"><div><span>01</span><b>SENTATE</b><i>✓</i></div><div><span>02</span><b>QUEDATE</b><i>✓</i></div><div><span>03</span><b>VENÍ</b><i>✓</i></div><div><span>04</span><b>SOLTÁ</b><i>✓</i></div><div><span>05</span><b>NO</b><i>✓</i></div></div><p>Cada uno mejora la seguridad y la convivencia diaria.</p></section></article>`,
`<article class="slide rule light">${logo}${page(5)}<section><div class="eyebrow">LA REGLA DE ORO</div><div class="formula"><b>CONSTANCIA</b><i>+</i><b>PACIENCIA</b><i>+</i><b>REFUERZO POSITIVO</b><i>=</i><strong>RESULTADOS</strong></div><p>Nunca uses el castigo físico. Los perros aprenden mejor cuando asocian el aprendizaje con algo bueno.</p><div class="session"><span>5—10</span><div><b>MINUTOS</b><small>Las sesiones cortas son más efectivas que las largas.</small></div></div></section></article>`,
`<article class="slide puppy"><img class="photo" src="../../media/backgrounds/raw/noppon-meenuch-FDKOuzy2QjM-unsplash.jpg" alt="Cachorro prestando atención">${logo}${page(6)}<section><div class="eyebrow">EL MEJOR MOMENTO</div><h2>¿Cuándo empezar?</h2><p class="lead">Lo antes posible,<br><em>pero nunca es tarde.</em></p><p>Los cachorros absorben comandos más rápido, pero los perros adultos también pueden aprender.</p><div class="tip"><b>LO IMPORTANTE</b> Respetar el ritmo de cada compañero.</div></section></article>`,
`<article class="slide cta dark">${page(7)}<section><img src="../../assets/logo-light.svg" alt="AYRES Pet Supply"><div class="line"></div><h2>¿Tu perro ya sabe alguno de estos comandos? <em>🐾</em></h2><p>Guardá este carrusel para empezar a practicar hoy.</p><div class="comment">💬 Contanos en los comentarios cuál fue el primero que aprendió.</div><footer><span>@ayres.petsupply</span><b>ayrespetsupply.com</b></footer></section></article>`
];
const n=Number(new URLSearchParams(location.search).get('slide')||1);document.querySelector('#app').innerHTML=slides[Math.min(Math.max(n,1),7)-1];
