const logo='<img class="logo" src="../../assets/logo-light.svg" alt="AYRES Pet Supply">';
const page=n=>`<div class="page"><b>${String(n).padStart(2,'0')}</b> / 09</div>`;
const slides=[
`<article class="slide cover"><img class="photo" src="assets/puppy-bowls.png" alt="Cachorro frente a dos comederos">${logo}${page(1)}<section><div class="eyebrow">CACHORROS · NUTRICIÓN</div><h1>¿Qué pasa si un cachorro come alimento <em>de adulto?</em></h1></section><div class="swipe">DESLIZÁ <b>→</b></div></article>`,
`<article class="slide light growth">${logo}${page(2)}<section><div class="eyebrow">NO ES LA MISMA FÓRMULA</div><h2>Está construyendo su futuro.</h2><div class="growth-grid"><div><i>🦴</i><b>HUESOS</b></div><div><i>💪</i><b>MÚSCULOS</b></div><div><i>🛡️</i><b>DEFENSAS</b></div><div><i>🧠</i><b>SISTEMA NERVIOSO</b></div></div><p>Un cachorro desarrolla todo esto <strong>a gran velocidad.</strong></p></section></article>`,
`<article class="slide photo-info energy"><img class="photo" src="assets/puppy-eating.png" alt="Cachorro comiendo su alimento">${logo}${page(3)}<section><div class="eyebrow">CRECER ≠ MANTENER</div><h2>Necesidades diferentes.</h2><div class="compare"><div class="active"><span>CACHORRO</span><b>ENERGÍA CONCENTRADA</b><b>PROTEÍNAS ADECUADAS</b><i>CRECIMIENTO</i></div><div><span>ADULTO</span><b>ENERGÍA DE MANTENIMIENTO</b><b>FÓRMULA PARA ORGANISMO DESARROLLADO</b><i>MANTENCIÓN</i></div></div><p>El alimento adulto está pensado para otra etapa de vida.</p></section></article>`,
`<article class="slide light minerals">${logo}${page(4)}<section><div class="eyebrow">EQUILIBRIO MINERAL</div><h2>Más no siempre es mejor.</h2><div class="balance"><div><span>Ca</span><b>CALCIO</b></div><i>↔</i><div><span>P</span><b>FÓSFORO</b></div></div><p>Requieren un equilibrio específico. Los desbalances también pueden afectar el desarrollo.</p><div class="warning">No agregues suplementos sin indicación veterinaria.</div></section></article>`,
`<article class="slide photo-info dha"><img class="photo" src="assets/puppy-vet.png" alt="Cachorro durante un control veterinario">${logo}${page(5)}<section><div class="eyebrow">DESARROLLO INTEGRAL</div><h2>Nutrientes que acompañan esta etapa.</h2><div class="nutrients"><div><i>🧠</i><b>DHA</b><span>Acompaña el aprendizaje y la maduración del sistema nervioso.</span></div><div><i>✨</i><b>ANTIOXIDANTES</b><span>Colaboran con el desarrollo de sus defensas.</span></div></div></section></article>`,
`<article class="slide accident"><img class="photo" src="assets/puppy-bowls.png" alt="Cachorro junto a comederos">${logo}${page(6)}<section><div class="eyebrow">AISLADO ≠ HABITUAL</div><h2>¿Comió del plato adulto?</h2><p>Una ingesta accidental no equivale a una dieta sostenida.</p><div class="callout"><b>EL PROBLEMA APARECE</b> Cuando la fórmula adulta reemplaza habitualmente la de cachorro.</div></section></article>`,
`<article class="slide photo-info multihome"><img class="photo" src="assets/separate-bowls.png" alt="Cachorro y perro adulto comiendo separados">${logo}${page(7)}<section><div class="eyebrow">VARIOS PERROS EN CASA</div><h2>Cada uno, su plato.</h2><div class="steps"><p><b>01</b> Separá los comederos.</p><p><b>02</b> Supervisá las comidas.</p><p><b>03</b> Evitá intercambios frecuentes.</p></div></section></article>`,
`<article class="slide dark transition">${logo}${page(8)}<section><div class="eyebrow">CAMBIO GRADUAL</div><h2>No cambies de golpe.</h2><div class="timeline"><div><b>1</b><span>FÓRMULA ACTUAL</span></div><i></i><div><b>2</b><span>TRANSICIÓN</span></div><i></i><div><b>3</b><span>NUEVA FÓRMULA</span></div></div><p>Hacé cualquier transición de forma gradual y según la indicación del veterinario.</p><div class="vet">✚ Observá siempre su digestión y apetito.</div></section></article>`,
`<article class="slide dark closing">${page(9)}<section><img src="../../assets/logo-light.svg" alt="AYRES Pet Supply"><div class="line"></div><h2>Elegí por <em>etapa, tamaño</em> y condición individual.</h2><p>Ante dudas de crecimiento o digestión, consultá con su veterinario.</p><div class="cta">Guardá este post si conviven perros de distintas edades.</div><footer><span>@ayres.petsupply</span><b>ayrespetsupply.com</b></footer></section></article>`
];
const n=Number(new URLSearchParams(location.search).get('slide')||1);document.querySelector('#app').innerHTML=slides[Math.min(Math.max(n,1),9)-1];
