const logo='<img class="logo" src="../../assets/logo-light.svg" alt="AYRES Pet Supply">';
const page=n=>`<div class="page"><b>${String(n).padStart(2,'0')}</b> / 09</div>`;
const slides=[
`<article class="slide cover"><img class="photo" src="assets/dog-embrace.png" alt="Perro abrazado a su persona">${logo}${page(1)}<section><div class="date">21 DE JULIO</div><h1>Día Mundial<br>del <em>Perro</em> 🐶❤️</h1><p>Hoy celebramos a quienes hacen del mundo <strong>un lugar más lindo.</strong></p></section><div class="swipe">DESLIZÁ <b>→</b></div></article>`,
`<article class="slide waiting"><img class="photo" src="../carrusel-06-adiestramiento/assets/training-cover.png" alt="Perro esperando a su persona">${logo}${page(2)}<section><div class="eyebrow">LA MEJOR BIENVENIDA</div><h2>A los que nos esperan detrás de la puerta…</h2><p>Como si volver a vernos fuera <em>el mejor momento de sus vidas.</em></p></section></article>`,
`<article class="slide light senses">${logo}${page(3)}<section><div class="eyebrow">NOS CONOCEN DE VERDAD</div><h2>A los que reconocen…</h2><div class="recognize"><div><span>01</span><b>NUESTROS PASOS</b></div><div><span>02</span><b>NUESTRO ÁNIMO</b></div><div><span>03</span><b>HASTA NUESTROS SILENCIOS</b></div></div><p>Sin que tengamos que decir una sola palabra.</p></section></article>`,
`<article class="slide adventure"><img class="photo" src="../carrusel-08-articulaciones/assets/dog-running.png" alt="Perro corriendo durante un paseo">${logo}${page(4)}<section><div class="eyebrow">AVENTURAS COTIDIANAS</div><h2>A los que convierten un paseo cualquiera en una aventura.</h2><div class="lines"><p>Una pelota en <em>el mejor regalo.</em></p><p>Y cualquier lugar en un hogar,<br><em>si estamos juntos.</em></p></div></section></article>`,
`<article class="slide light traces">${logo}${page(5)}<section><div class="eyebrow">LAS MARCAS MÁS LINDAS</div><h2>A los que dejan…</h2><div class="trace"><i>〰️</i><p>Pelos en la ropa…</p></div><div class="trace"><i>🐾</i><p>Huellitas en el piso…</p></div><div class="trace heart"><i>❤️</i><p>Y recuerdos para siempre<br><strong>en el corazón.</strong></p></div></section></article>`,
`<article class="slide companion"><img class="photo" src="assets/dog-embrace.png" alt="Perro acompañando a su persona">${logo}${page(6)}<section><div class="eyebrow">SIEMPRE CERCA</div><h2>A los que nos acompañan en los días felices.</h2><p>Y se quedan <em>todavía más cerca</em> cuando las cosas no salen bien.</p></section></article>`,
`<article class="slide life"><img class="photo" src="../carrusel-08-articulaciones/assets/senior-dog.png" alt="Perro mayor descansando">${logo}${page(7)}<section><div class="eyebrow">AMOR PARA TODA LA VIDA</div><h2>Ellos no saben cuánto dura una vida.</h2><p>Solo saben amarnos<br><em>durante toda la suya.</em></p></section></article>`,
`<article class="slide dark thanks">${logo}${page(8)}<section><div class="eyebrow">POR TODO LO COMPARTIDO</div><h2><span>Por cada bienvenida.</span><span>Cada mirada.</span><span>Cada paseo.</span><span>Cada momento compartido…</span></h2><div class="thank-you">Gracias. <b>❤️</b></div></section></article>`,
`<article class="slide dark closing">${page(9)}<section><img src="../../assets/logo-light.svg" alt="AYRES Pet Supply"><div class="line"></div><h2>Feliz Día Mundial<br><em>del Perro</em></h2><p>A todos los que alguna vez nos demostraron que el amor también puede tener <strong>cuatro patas.</strong> 🐾</p><div class="cta">Compartí una foto de tu compañero y etiquetanos.</div><footer><span>@ayres.petsupply</span><b>ayrespetsupply.com</b></footer></section></article>`
];
const n=Number(new URLSearchParams(location.search).get('slide')||1);document.querySelector('#app').innerHTML=slides[Math.min(Math.max(n,1),9)-1];
