const logo='<img class="logo" src="../../assets/logo-light.svg" alt="AYRES Pet Supply">';
const page=n=>`<div class="page"><b>${String(n).padStart(2,'0')}</b> / 09</div>`;
const tip=(icon,label,text)=>`<div class="tip"><i>${icon}</i><div><b>${label}</b><span>${text}</span></div></div>`;
const slides=[
`<article class="slide cover"><img class="photo" src="assets/curious-cat.png" alt="Gato curioso explorando una casa segura">${logo}${page(1)}<section><div class="eyebrow">CUIDADO Y BIENESTAR</div><h1>Gato curioso,<br><em>casa segura.</em></h1><p><strong>7 ajustes</strong> que hacen la diferencia.</p></section><div class="swipe">DESLIZÁ <b>→</b></div></article>`,
`<article class="slide light nature">${logo}${page(2)}<section><div class="eyebrow">CURIOSIDAD NATURAL</div><h2>Explorar no es un defecto.</h2><div class="behaviors"><div><i>🔎</i><b>EXPLORAR</b></div><div><i>🧗</i><b>TREPAR</b></div><div><i>👀</i><b>OBSERVAR</b></div></div><p>Son conductas naturales que <strong>estimulan su mente</strong> y le permiten entender el ambiente.</p><div class="highlight">La clave no es frenarlo: es darle un espacio seguro.</div></section></article>`,
`<article class="slide dark storage">${logo}${page(3)}<section><div class="eyebrow">AJUSTE 01 · GUARDÁ</div><h2>Fuera de su alcance.</h2>${tip('💊','MEDICAMENTOS','Guardalos siempre en muebles cerrados.')}${tip('🧴','PRODUCTOS DE LIMPIEZA','Evitá estantes abiertos o envases accesibles.')}${tip('🧷','OBJETOS PEQUEÑOS','Lo que rueda o cuelga puede parecer un juguete.')}</section></article>`,
`<article class="slide light toxins">${logo}${page(4)}<section><div class="eyebrow">AJUSTE 02 · REVISÁ</div><h2>No todo lo cotidiano es seguro.</h2><div class="split"><div><i>🪴</i><b>PLANTAS</b><p>Verificá cada especie antes de dejarla a su alcance.</p></div><div><i>🍽️</i><b>ALIMENTOS</b><p>No compartas comida sin comprobar que sea apta para gatos.</p></div></div><div class="warning">Algunos productos cotidianos pueden resultar tóxicos.</div></section></article>`,
`<article class="slide windows"><img class="photo" src="assets/curious-cat.png" alt="Gato junto a una ventana con red">${logo}${page(5)}<section><div class="eyebrow">AJUSTE 03 · PROTEGÉ</div><h2>Ventanas y balcones.</h2><p>Usá redes <strong>firmes y bien instaladas.</strong></p><div class="callout"><b>IMPORTANTE</b> La altura no elimina el riesgo de una caída.</div></section></article>`,
`<article class="slide dark cables">${logo}${page(6)}<section><div class="eyebrow">AJUSTE 04 · ASEGURÁ</div><h2>Cables fuera de juego.</h2><div class="cable-visual"><span>🔌</span><i></i><span>🐈</span></div><p>Ocultalos o asegurarlos para que no pueda morderlos.</p><div class="highlight"><b>SUMÁ ALTERNATIVAS</b> Ofrecé juguetes seguros para evitar que los busque por aburrimiento.</div></section></article>`,
`<article class="slide light explore">${logo}${page(7)}<section><div class="eyebrow">AJUSTE 05 · ENRIQUECÉ</div><h2>Exploración segura.</h2><div class="grid">${['📦|CAJAS','🌀|TÚNELES','🪵|RASCADORES','🧱|ESTANTES','⬆️|PUNTOS ALTOS'].map(x=>{const [a,b]=x.split('|');return `<div><i>${a}</i><b>${b}</b></div>`}).join('')}</div><p>Creá recorridos y refugios desde donde pueda jugar, esconderse y observar.</p></section></article>`,
`<article class="slide dark play">${logo}${page(8)}<section><div class="eyebrow">AJUSTES 06 + 07 · ROTÁ Y JUGÁ</div><h2>Novedad, sin saturarlo.</h2><div class="rotation"><div><span>01</span><b>ROTÁ LOS JUGUETES</b><p>No hace falta ofrecerlos todos al mismo tiempo.</p></div><div><span>02</span><b>SESIONES CORTAS</b><p>Sumá momentos breves de juego todos los días.</p></div></div><div class="highlight">La novedad controlada mantiene su interés.</div></section></article>`,
`<article class="slide dark closing">${page(9)}<section><img src="../../assets/logo-light.svg" alt="AYRES Pet Supply"><div class="line"></div><h2>No apagues<br>su <em>curiosidad.</em></h2><p>Diseñá un ambiente donde pueda expresarla con menos riesgos.</p><div class="cta">Guardá esta checklist y compartila con quien está preparando su casa para un gato.</div><footer><span>@ayres.petsupply</span><b>ayrespetsupply.com</b></footer></section></article>`
];
const n=Number(new URLSearchParams(location.search).get('slide')||1);document.querySelector('#app').innerHTML=slides[Math.min(Math.max(n,1),9)-1];
