const logo='<img class="logo" src="../../assets/logo-light.svg" alt="AYRES Pet Supply">';
const page=n=>`<div class="page"><b>${String(n).padStart(2,'0')}</b> / 09</div>`;
const items=data=>`<div class="items">${data.map(([icon,text])=>`<div><i>${icon}</i><span>${text}</span></div>`).join('')}</div>`;
const slides=[
`<article class="slide cover"><img class="photo" src="assets/world-dog-day.png" alt="Persona compartiendo un momento con su perro">${logo}${page(1)}<section><div class="date">21 DE JULIO</div><h1>Día Mundial<br>del <em>Perro</em> 🐶</h1><p>Hoy celebramos su amor.<br><strong>Todos los días cuidamos su bienestar.</strong></p></section><div class="swipe">DESLIZÁ <b>→</b></div></article>`,
`<article class="slide light family">${logo}${page(2)}<section><div class="eyebrow">TODOS SON ÚNICOS</div><h2>No importa si es grande, pequeño, mestizo o de raza.</h2><div class="dogs"><span>🐕</span><span>🐶</span><span>🐕‍🦺</span><span>🦮</span></div><p>Para él, <strong>vos sos su familia</strong> y una parte enorme de su mundo.</p></section></article>`,
`<article class="slide reunion"><img class="photo" src="../carrusel-06-adiestramiento/assets/training-cover.png" alt="Perro mirando con alegría a su persona">${logo}${page(3)}<section><div class="eyebrow">AMOR SIN RELOJ</div><h2>Nos reciben como si hubiéramos estado fuera durante años…</h2><p>Aunque solo salimos <em>cinco minutos.</em> ❤️</p></section></article>`,
`<article class="slide dark care">${logo}${page(4)}<section><div class="eyebrow">TENENCIA RESPONSABLE</div><h2>Quererlo es mucho más que darle cariño.</h2><p>También necesita:</p>${items([['🥣','Alimentación adecuada'],['💧','Agua fresca'],['🎾','Ejercicio'],['🩺','Atención veterinaria'],['🌙','Descanso y estimulación']])}</section></article>`,
`<article class="slide light listen">${logo}${page(5)}<section><div class="eyebrow">APRENDER A ESCUCHAR</div><h2>También se comunica con vos.</h2><div class="language"><div><i>👀</i><b>MIRADA</b></div><div><i>🐕</i><b>POSTURA</b></div><div><i>〰️</i><b>COLA</b></div><div><i>💭</i><b>CONDUCTA</b></div></div><p>Su postura, mirada, cola y comportamiento pueden decirnos <strong>cómo se siente.</strong></p></section></article>`,
`<article class="slide dark essentials">${logo}${page(6)}<section><div class="eyebrow">CUIDADOS ESENCIALES</div><h2>Nunca debería faltarle:</h2>${items([['🏷️','Identificación'],['💉','Vacunas y controles'],['🛡️','Protección contra parásitos'],['🦮','Paseos seguros'],['🤝','Tiempo de calidad']])}</section></article>`,
`<article class="slide adoption"><img class="photo" src="../carrusel-08-articulaciones/assets/senior-dog.png" alt="Perro esperando una familia">${logo}${page(7)}<section><div class="eyebrow">UNA FAMILIA PARA CADA UNO</div><h2>Muchos todavía esperan.</h2><p>Este día también nos invita a hablar sobre los perros que todavía esperan una familia.</p><div class="callout"><b>SI ESTÁS PREPARADO</b> Considerá la adopción responsable.</div></section></article>`,
`<article class="slide light help">${logo}${page(8)}<section><div class="eyebrow">TODOS PODEMOS AYUDAR</div><h2>¿No podés adoptar?</h2><p>También podés hacer una diferencia:</p>${items([['📣','Difundiendo animales en adopción'],['🏠','Colaborando con refugios'],['🥫','Donando alimento o medicamentos'],['🐾','Ofreciendo tránsito responsable']])}</section></article>`,
`<article class="slide dark closing">${page(9)}<section><img src="../../assets/logo-light.svg" alt="AYRES Pet Supply"><div class="line"></div><p>HOY CELEBRALO CON LO QUE MÁS VALORA:</p><h2><span>Tu tiempo.</span><span>Tu cuidado.</span><span>Tu compañía.</span></h2><div class="wish">¡Feliz Día Mundial del Perro! 🐾</div><div class="cta">Subí una foto a tus historias y etiquetanos.</div><footer><span>@ayres.petsupply</span><b>ayrespetsupply.com</b></footer></section></article>`
];
const n=Number(new URLSearchParams(location.search).get('slide')||1);document.querySelector('#app').innerHTML=slides[Math.min(Math.max(n,1),9)-1];
